### Overview

Na základe metódy feature importance pre xgboost som vybrala 5 najdôležitejších atribútov a na ich základe som vytvorila dátové súbory, s ktorými som ďalej pracovala

In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')
from xgboost import XGBClassifier
from sklearn.model_selection import GridSearchCV


from sklearn.model_selection import train_test_split
from sklearn.metrics import (accuracy_score,precision_score,recall_score,f1_score,roc_auc_score,confusion_matrix)

In [2]:
TW_500= pd.read_csv(
    "../classification/Twitter/Relative_labeling/sigma=500/Twitter-Relative-Sigma-500.data",
    sep=",",
    header=None
)

TW_1000= pd.read_csv(
    "../classification/Twitter/Relative_labeling/sigma=1000/Twitter-Relative-Sigma-1000.data",
    sep=",",
    header=None
)
TW_1500= pd.read_csv(
    "../classification/Twitter/Relative_labeling/sigma=1500/Twitter-Relative-Sigma-1500.data",
    sep=",",
    header=None
)
groups = ["NCD", 'AI', 'AS(NA)', 'BL',
         'NAC', 'AS(NAC)', 'CS', 'AT', 'NA','ADL', 'NAD']

columns = []
for group in groups:
    for t in range(7):
        columns.append(f"{group}_{t}")

columns.append("label") 

TW_500.columns = columns
TW_1000.columns = columns
TW_1500.columns = columns

In [19]:
top_features = ['NCD','NAD','NAC','AS(NAC)','NA', 'label']

selected_columns = [
    col for col in TW_500.columns 
    if any(col.startswith(f + '_') for f in top_features)
]

Selected_500 = TW_500[selected_columns]
Selected_500['label']=TW_500['label']

print("Number of features:", len(selected_columns))
Selected_500.columns

Number of features: 35

Index(['NCD_0', 'NCD_1', 'NCD_2', 'NCD_3', 'NCD_4', 'NCD_5', 'NCD_6', 'NAC_0',
       'NAC_1', 'NAC_2', 'NAC_3', 'NAC_4', 'NAC_5', 'NAC_6', 'AS(NAC)_0',
       'AS(NAC)_1', 'AS(NAC)_2', 'AS(NAC)_3', 'AS(NAC)_4', 'AS(NAC)_5',
       'AS(NAC)_6', 'NA_0', 'NA_1', 'NA_2', 'NA_3', 'NA_4', 'NA_5', 'NA_6',
       'NAD_0', 'NAD_1', 'NAD_2', 'NAD_3', 'NAD_4', 'NAD_5', 'NAD_6', 'label'],
      dtype='object')

In [20]:
Selected_500.head(2)

,NCD_0,NCD_1,NCD_2,NCD_3,NCD_4,NCD_5,NCD_6,NAC_0,NAC_1,NAC_2,...,NA_5,NA_6,NAD_0,NAD_1,NAD_2,NAD_3,NAD_4,NAD_5,NAD_6,label
0,889,939,960,805,805,1143,1121,889,939,960,...,788,783,889,939,960,805,805,1143,1121,0.0
1,542,473,504,626,647,795,832,542,473,504,...,616,647,542,473,504,626,647,795,832,1.0

In [22]:
top_features = ['NCD','NAC', 'AS(NAC)', 'AS(NA)', 'NAD','label']

selected_columns = [
    col for col in TW_1000.columns 
    if any(col.startswith(f + '_') for f in top_features)
]

Selected_1000 = TW_1000[selected_columns]
Selected_1000['label']=TW_1000['label']

print("Number of features:", len(selected_columns))
Selected_1000.columns

Number of features: 35

Index(['NCD_0', 'NCD_1', 'NCD_2', 'NCD_3', 'NCD_4', 'NCD_5', 'NCD_6',
       'AS(NA)_0', 'AS(NA)_1', 'AS(NA)_2', 'AS(NA)_3', 'AS(NA)_4', 'AS(NA)_5',
       'AS(NA)_6', 'NAC_0', 'NAC_1', 'NAC_2', 'NAC_3', 'NAC_4', 'NAC_5',
       'NAC_6', 'AS(NAC)_0', 'AS(NAC)_1', 'AS(NAC)_2', 'AS(NAC)_3',
       'AS(NAC)_4', 'AS(NAC)_5', 'AS(NAC)_6', 'NAD_0', 'NAD_1', 'NAD_2',
       'NAD_3', 'NAD_4', 'NAD_5', 'NAD_6', 'label'],
      dtype='object')

In [23]:
Selected_1000.head(2)

,NCD_0,NCD_1,NCD_2,NCD_3,NCD_4,NCD_5,NCD_6,AS(NA)_0,AS(NA)_1,AS(NA)_2,...,AS(NAC)_5,AS(NAC)_6,NAD_0,NAD_1,NAD_2,NAD_3,NAD_4,NAD_5,NAD_6,label
0,889,939,960,805,805,1143,1121,0.000730,0.000777,0.000757,...,0.000577,0.000556,889,939,960,805,805,1143,1121,0.0
1,542,473,504,626,647,795,832,0.000517,0.000460,0.000474,...,0.000412,0.000434,542,473,504,626,647,795,832,0.0

In [24]:
top_features = ['NCD','NAC', 'NAD', 'AS(NAC)', 'AS(NA)','label']

selected_columns = [
    col for col in TW_1500.columns 
    if any(col.startswith(f + '_') for f in top_features)
]

Selected_1500 = TW_1500[selected_columns]
Selected_1500['label']=TW_1500['label']
print("Number of features:", len(selected_columns))
Selected_1500.columns

Number of features: 35

Index(['NCD_0', 'NCD_1', 'NCD_2', 'NCD_3', 'NCD_4', 'NCD_5', 'NCD_6',
       'AS(NA)_0', 'AS(NA)_1', 'AS(NA)_2', 'AS(NA)_3', 'AS(NA)_4', 'AS(NA)_5',
       'AS(NA)_6', 'NAC_0', 'NAC_1', 'NAC_2', 'NAC_3', 'NAC_4', 'NAC_5',
       'NAC_6', 'AS(NAC)_0', 'AS(NAC)_1', 'AS(NAC)_2', 'AS(NAC)_3',
       'AS(NAC)_4', 'AS(NAC)_5', 'AS(NAC)_6', 'NAD_0', 'NAD_1', 'NAD_2',
       'NAD_3', 'NAD_4', 'NAD_5', 'NAD_6', 'label'],
      dtype='object')

In [25]:
Selected_1500.head(2)

,NCD_0,NCD_1,NCD_2,NCD_3,NCD_4,NCD_5,NCD_6,AS(NA)_0,AS(NA)_1,AS(NA)_2,...,AS(NAC)_5,AS(NAC)_6,NAD_0,NAD_1,NAD_2,NAD_3,NAD_4,NAD_5,NAD_6,label
0,889,939,960,805,805,1143,1121,0.000730,0.000777,0.000757,...,0.000577,0.000556,889,939,960,805,805,1143,1121,0.0
1,542,473,504,626,647,795,832,0.000517,0.000460,0.000474,...,0.000412,0.000434,542,473,504,626,647,795,832,0.0